"""add equity sale fields to redemptions

Revision ID: 8687b06004fa
Revises: 5a679675afb2
Create Date: 2026-08-18 13:45:29.268570+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '8687b06004fa'
down_revision: Union[str, None] = '5a679675afb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redemptions', sa.Column('holding_id', sa.UUID(), nullable=True))
    op.add_column('redemptions', sa.Column('units_sold', sa.Float(), nullable=True))
    op.add_column('redemptions', sa.Column('sale_price', sa.Float(), nullable=True))
    op.add_column('redemptions', sa.Column('cost_price_at_sale', sa.Float(), nullable=True))
    op.add_column('redemptions', sa.Column('realized_gain', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'redemptions', 'portfolio_holdings', ['holding_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'redemptions', type_='foreignkey')
    op.drop_column('redemptions', 'realized_gain')
    op.drop_column('redemptions', 'cost_price_at_sale')
    op.drop_column('redemptions', 'sale_price')
    op.drop_column('redemptions', 'units_sold')
    op.drop_column('redemptions', 'holding_id')
    # ### end Alembic commands ###