"""baseline schema

Revision ID: 5a679675afb2
Revises: 
Create Date: 2026-08-16 13:49:38.995090+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5a679675afb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premature_penalty_pct', sa.Float(), nullable=False),
    sa.Column('management_fee_pct', sa.Float(), nullable=False),
    sa.Column('performance_fee_pct', sa.Float(), nullable=False),
    sa.Column('liquidation_notice_days', sa.Integer(), nullable=False),
    sa.Column('min_investment_ngn', sa.Float(), nullable=False),
    sa.Column('min_tenure_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bank', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('can_manage_staff_users', sa.Boolean(), nullable=False),
    sa.Column('can_configure_roles', sa.Boolean(), nullable=False),
    sa.Column('can_manage_clients', sa.Boolean(), nullable=False),
    sa.Column('can_approve_kyc', sa.Boolean(), nullable=False),
    sa.Column('can_manage_subscriptions', sa.Boolean(), nullable=False),
    sa.Column('can_manage_redemptions', sa.Boolean(), nullable=False),
    sa.Column('can_enter_valuations', sa.Boolean(), nullable=False),
    sa.Column('can_manage_nav', sa.Boolean(), nullable=False),
    sa.Column('can_configure_workflows', sa.Boolean(), nullable=False),
    sa.Column('can_manage_products', sa.Boolean(), nullable=False),
    sa.Column('can_manage_fees', sa.Boolean(), nullable=False),
    sa.Column('can_manage_certificates', sa.Boolean(), nullable=False),
    sa.Column('can_manage_maturity', sa.Boolean(), nullable=False),
    sa.Column('can_manage_payments', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('can_view_audit_log', sa.Boolean(), nullable=False),
    sa.Column('can_manage_system_settings', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('whatsapp', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('regulator', sa.String(length=255), nullable=False),
    sa.Column('alert_active', sa.Boolean(), nullable=False),
    sa.Column('alert_message', sa.Text(), nullable=True),
    sa.Column('alert_severity', sa.Enum('info', 'warning', 'critical', name='alert_severity_enum'), nullable=False),
    sa.Column('alert_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('show_portfolio_breakdown', sa.Boolean(), nullable=False),
    sa.Column('md_signature_url', sa.Text(), nullable=True),
    sa.Column('secretary_signature_url', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.Enum('individual', 'joint', 'minor', 'corporate', name='account_type_enum'), nullable=False),
    sa.Column('kyc_status', sa.Enum('not_submitted', 'pending', 'approved', 'denied', name='kyc_status_enum'), nullable=False),
    sa.Column('kyc_denied_reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('temp_password_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_account_type', 'users', ['account_type'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('ix_users_kyc_status', 'users', ['kyc_status'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trigger', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'junior_admin', name='admin_role_enum'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('temp_password_active', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('staff_role_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['staff_role_id'], ['staff_roles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('kyc_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'denied', name='kyc_submission_status_enum'), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('d365_record_id', sa.String(length=100), nullable=True),
    sa.Column('d365_synced', sa.Boolean(), nullable=False),
    sa.Column('d365_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('lga', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('employer', sa.String(length=255), nullable=True),
    sa.Column('annual_income', sa.String(length=50), nullable=True),
    sa.Column('investment_experience', sa.String(length=50), nullable=True),
    sa.Column('risk_profile', sa.String(length=50), nullable=True),
    sa.Column('pep_status', sa.Boolean(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('rc_number', sa.String(length=100), nullable=True),
    sa.Column('company_address', sa.Text(), nullable=True),
    sa.Column('signatories', sa.JSON(), nullable=True),
    sa.Column('id_document_url', sa.Text(), nullable=True),
    sa.Column('utility_bill_url', sa.Text(), nullable=True),
    sa.Column('passport_photo_url', sa.Text(), nullable=True),
    sa.Column('cac_certificate_url', sa.Text(), nullable=True),
    sa.Column('board_resolution_url', sa.Text(), nullable=True),
    sa.Column('memorandum_url', sa.Text(), nullable=True),
    sa.Column('scuml_certificate_url', sa.Text(), nullable=True),
    sa.Column('tin_certificate_url', sa.Text(), nullable=True),
    sa.Column('board_resolution_director_signature_url', sa.Text(), nullable=True),
    sa.Column('board_resolution_secretary_signature_url', sa.Text(), nullable=True),
    sa.Column('minor_passport_photo_url', sa.Text(), nullable=True),
    sa.Column('minor_birth_certificate_url', sa.Text(), nullable=True),
    sa.Column('joint_passport_photo_url', sa.Text(), nullable=True),
    sa.Column('joint_id_document_url', sa.Text(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_submissions_user_id'), 'kyc_submissions', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('product_type', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('discretionary', sa.String(length=50), nullable=False),
    sa.Column('min_amount', sa.Float(), nullable=False),
    sa.Column('min_amount_display', sa.String(length=50), nullable=False),
    sa.Column('roi', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('risk', sa.String(length=50), nullable=False),
    sa.Column('target_investors', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payment_account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_account_id'], ['payment_accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_payment_account_id'), 'products', ['payment_account_id'], unique=False)
    op.create_table('workflow_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('step_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_created_at'), 'workflow_instances', ['created_at'], unique=False)
    op.create_index('ix_workflow_instances_one_active_per_record', 'workflow_instances', ['record_type', 'record_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'in_progress')"))
    op.create_table('workflow_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('required_permission', sa.String(length=100), nullable=False),
    sa.Column('available_actions', sa.String(length=200), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('notify_ceo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('performed_by_name', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('instrument_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('price_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('entered_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_name', 'price_date', name='uq_instrument_price_per_day')
    )
    op.create_index(op.f('ix_instrument_prices_instrument_name'), 'instrument_prices', ['instrument_name'], unique=False)
    op.create_table('nav_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('period_label', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('nav_per_unit', sa.Float(), nullable=True),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('cumulative_pct', sa.Float(), nullable=True),
    sa.Column('total_aum', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('entered_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entered_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'period_label', name='uq_nav_product_period')
    )
    op.create_index('ix_nav_period_end', 'nav_records', ['period_end'], unique=False)
    op.create_index('ix_nav_product_id', 'nav_records', ['product_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'pending_review', 'active', 'matured', 'redeemed', 'denied', name='subscription_status_enum'), nullable=False),
    sa.Column('denial_reason', sa.Text(), nullable=True),
    sa.Column('receipt_url', sa.Text(), nullable=True),
    sa.Column('receipt_data', sa.Text(), nullable=True),
    sa.Column('receipt_filename', sa.String(length=255), nullable=True),
    sa.Column('receipt_mime_type', sa.String(length=100), nullable=True),
    sa.Column('receipt_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('d365_record_id', sa.String(length=100), nullable=True),
    sa.Column('d365_synced', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('matured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subs_product_id', 'subscriptions', ['product_id'], unique=False)
    op.create_index('ix_subs_status', 'subscriptions', ['status'], unique=False)
    op.create_index('ix_subs_submitted_at', 'subscriptions', ['submitted_at'], unique=False)
    op.create_index('ix_subs_user_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_subscriptions_reference'), 'subscriptions', ['reference'], unique=True)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.String(length=100), nullable=False),
    sa.Column('roi', sa.String(length=100), nullable=True),
    sa.Column('issue_date', sa.String(length=20), nullable=False),
    sa.Column('maturity_date', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('cert_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('issued', 'emailed', 'revoked', name='cert_status_enum'), nullable=False),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('holding_type', sa.String(length=20), nullable=False),
    sa.Column('instrument_name', sa.String(length=200), nullable=False),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('principal', sa.Float(), nullable=True),
    sa.Column('roi_pct', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_holdings_subscription_id'), 'portfolio_holdings', ['subscription_id'], unique=False)
    op.create_table('portfolio_valuations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('valuation_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equities_value', sa.Float(), nullable=False),
    sa.Column('fixed_income_value', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_valuations_subscription_id'), 'portfolio_valuations', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_portfolio_valuations_valuation_date'), 'portfolio_valuations', ['valuation_date'], unique=False)
    op.create_table('redemptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('penalty', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('is_premature', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'rejected', name='redemption_status_enum'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index('ix_redemptions_status', 'redemptions', ['status'], unique=False)
    op.create_index(op.f('ix_redemptions_user_id'), 'redemptions', ['user_id'], unique=False)
    op.create_index('ix_redemptions_user_status', 'redemptions', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_redemptions_user_status', table_name='redemptions')
    op.drop_index(op.f('ix_redemptions_user_id'), table_name='redemptions')
    op.drop_index('ix_redemptions_status', table_name='redemptions')
    op.drop_table('redemptions')
    op.drop_index(op.f('ix_portfolio_valuations_valuation_date'), table_name='portfolio_valuations')
    op.drop_index(op.f('ix_portfolio_valuations_subscription_id'), table_name='portfolio_valuations')
    op.drop_table('portfolio_valuations')
    op.drop_index(op.f('ix_portfolio_holdings_subscription_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_reference'), table_name='subscriptions')
    op.drop_index('ix_subs_user_status', table_name='subscriptions')
    op.drop_index('ix_subs_submitted_at', table_name='subscriptions')
    op.drop_index('ix_subs_status', table_name='subscriptions')
    op.drop_index('ix_subs_product_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_nav_product_id', table_name='nav_records')
    op.drop_index('ix_nav_period_end', table_name='nav_records')
    op.drop_table('nav_records')
    op.drop_index(op.f('ix_instrument_prices_instrument_name'), table_name='instrument_prices')
    op.drop_table('instrument_prices')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('announcements')
    op.drop_table('workflow_steps')
    op.drop_index('ix_workflow_instances_one_active_per_record', table_name='workflow_instances', postgresql_where=sa.text("status IN ('pending', 'in_progress')"))
    op.drop_index(op.f('ix_workflow_instances_created_at'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_index(op.f('ix_products_payment_account_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notif_user_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_kyc_submissions_user_id'), table_name='kyc_submissions')
    op.drop_table('kyc_submissions')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_table('workflows')
    op.drop_index('ix_users_kyc_status', table_name='users')
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_account_type', table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('staff_roles')
    op.drop_table('payment_accounts')
    op.drop_table('fee_config')
    # ### end Alembic commands ###