"""add extra_data to kyc_submissions

Revision ID: 4b6e461f682d
Revises: ab2c417ec849
Create Date: 2026-03-13 08:50:44.042619+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4b6e461f682d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
#down_revision: Union[str, None] = 'ab2c417ec849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nav_records', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('nav_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('nav_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_nav_period_end', table_name='nav_records')
    op.create_index('ix_nav_period_end', 'nav_records', ['period_end'], unique=False)
    op.drop_column('products', 'initial_nav')
    op.drop_column('subscriptions', 'nav_at_entry')
    op.drop_column('subscriptions', 'units_allocated')
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('units_allocated', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('nav_at_entry', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('initial_nav', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('100.0'), autoincrement=False, nullable=True))
    op.drop_index('ix_nav_period_end', table_name='nav_records')
    op.create_index('ix_nav_period_end', 'nav_records', [sa.text('period_end DESC')], unique=False)
    op.alter_column('nav_records', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('nav_records', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('nav_records', 'source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    # ### end Alembic commands ###