"""fix audit log and admin fk ondelete behavior

Revision ID: 58291fa77558
Revises: 3cfd900c519b
Create Date: 2026-08-06 05:53:33.007173+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '58291fa77558'
down_revision: Union[str, None] = '3cfd900c519b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('admin_users_created_by_fkey', 'admin_users', type_='foreignkey')
    op.create_foreign_key(
        'admin_users_created_by_fkey', 'admin_users', 'admin_users', ['created_by'], ['id'], ondelete='SET NULL'
    )

    op.drop_constraint('announcements_created_by_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key(
        'announcements_created_by_fkey', 'announcements', 'admin_users', ['created_by'], ['id'], ondelete='SET NULL'
    )

    op.drop_constraint('audit_log_performed_by_fkey', 'audit_log', type_='foreignkey')
    op.create_foreign_key(
        'audit_log_performed_by_fkey', 'audit_log', 'admin_users', ['performed_by'], ['id'], ondelete='SET NULL'
    )

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as previous migrations.


def downgrade() -> None:
    op.drop_constraint('audit_log_performed_by_fkey', 'audit_log', type_='foreignkey')
    op.create_foreign_key('audit_log_performed_by_fkey', 'audit_log', 'admin_users', ['performed_by'], ['id'])

    op.drop_constraint('announcements_created_by_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key('announcements_created_by_fkey', 'announcements', 'admin_users', ['created_by'], ['id'])

    op.drop_constraint('admin_users_created_by_fkey', 'admin_users', type_='foreignkey')
    op.create_foreign_key('admin_users_created_by_fkey', 'admin_users', 'admin_users', ['created_by'], ['id'])
