"""add workflow instance duplicate guard

Revision ID: 016be04393b3
Revises: 58291fa77558
Create Date: 2026-08-08 05:27:57.308043+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '016be04393b3'
down_revision: Union[str, None] = '58291fa77558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enforces at most one active (pending/in_progress) WorkflowInstance per
    # (record_type, record_id) at the database level — see models.py's
    # WorkflowInstance.__table_args__ for the full explanation. This is
    # what actually closes the race condition; the application-level check
    # in _fire_workflow() is just a fast-path.
    op.create_index(
        'ix_workflow_instances_one_active_per_record',
        'workflow_instances',
        ['record_type', 'record_id'],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'in_progress')"),
    )

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as previous migrations.


def downgrade() -> None:
    op.drop_index(
        'ix_workflow_instances_one_active_per_record',
        table_name='workflow_instances',
        postgresql_where=sa.text("status IN ('pending', 'in_progress')"),
    )
