"""add scuml and tin certificate urls

Revision ID: 9db261e83142
Revises: 016be04393b3
Create Date: 2026-08-08 06:04:57.962055+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9db261e83142'
down_revision: Union[str, None] = '016be04393b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('kyc_submissions', sa.Column('scuml_certificate_url', sa.Text(), nullable=True))
    op.add_column('kyc_submissions', sa.Column('tin_certificate_url', sa.Text(), nullable=True))

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_column('kyc_submissions', 'tin_certificate_url')
    op.drop_column('kyc_submissions', 'scuml_certificate_url')
