"""add certificate maturity payment permission flags

Revision ID: 970daf785701
Revises: 140a2853407c
Create Date: 2026-08-14 15:51:57.312597+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '970daf785701'
down_revision: Union[str, None] = '140a2853407c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default=sa.false() is required on all three: these are NOT NULL
    # columns being added to a table that already has rows, so Postgres needs
    # a value for those existing roles. Defaults to False, meaning existing
    # roles don't silently gain new permissions — an admin has to grant each
    # one deliberately under Roles & Permissions.
    op.add_column('staff_roles', sa.Column('can_manage_certificates', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('staff_roles', sa.Column('can_manage_maturity', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('staff_roles', sa.Column('can_manage_payments', sa.Boolean(), nullable=False, server_default=sa.false()))

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_column('staff_roles', 'can_manage_payments')
    op.drop_column('staff_roles', 'can_manage_maturity')
    op.drop_column('staff_roles', 'can_manage_certificates')
