"""add staff roles table

Revision ID: 2f68c80a010a
Revises: 716b487d162b
Create Date: 2026-08-04 20:40:54.352066+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '2f68c80a010a'
down_revision: Union[str, None] = '716b487d162b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK_NAME = "fk_admin_users_staff_role_id"


def upgrade() -> None:
    op.create_table(
        'staff_roles',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('department', sa.String(length=100), nullable=True),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('can_manage_staff_users', sa.Boolean(), nullable=False),
        sa.Column('can_configure_roles', sa.Boolean(), nullable=False),
        sa.Column('can_manage_clients', sa.Boolean(), nullable=False),
        sa.Column('can_approve_kyc', sa.Boolean(), nullable=False),
        sa.Column('can_manage_subscriptions', sa.Boolean(), nullable=False),
        sa.Column('can_manage_redemptions', sa.Boolean(), nullable=False),
        sa.Column('can_enter_valuations', sa.Boolean(), nullable=False),
        sa.Column('can_manage_nav', sa.Boolean(), nullable=False),
        sa.Column('can_configure_workflows', sa.Boolean(), nullable=False),
        sa.Column('can_manage_products', sa.Boolean(), nullable=False),
        sa.Column('can_manage_fees', sa.Boolean(), nullable=False),
        sa.Column('can_view_reports', sa.Boolean(), nullable=False),
        sa.Column('can_view_audit_log', sa.Boolean(), nullable=False),
        sa.Column('can_manage_system_settings', sa.Boolean(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
    )
    # staff_roles is brand new (no existing rows), so nullable=False booleans
    # above are fine without a server_default — unlike the mfa/temp_password
    # migration, there's nothing pre-existing to backfill.

    op.add_column('admin_users', sa.Column('staff_role_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        FK_NAME, 'admin_users', 'staff_roles', ['staff_role_id'], ['id'], ondelete='SET NULL'
    )

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as the previous migration. Handle it
    # deliberately on its own later, not as a side effect of this change.


def downgrade() -> None:
    op.drop_constraint(FK_NAME, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'staff_role_id')
    op.drop_table('staff_roles')
