"""add private portfolio holdings and valuations

Revision ID: ae49a2080cf2
Revises: 5ca396c7c24c
Create Date: 2026-08-13 12:25:30.127455+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ae49a2080cf2'
down_revision: Union[str, None] = '5ca396c7c24c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'instrument_prices',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('instrument_name', sa.String(length=200), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('price_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('source', sa.String(length=20), nullable=False),
        sa.Column('entered_by', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['entered_by'], ['admin_users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('instrument_name', 'price_date', name='uq_instrument_price_per_day'),
    )
    op.create_index(op.f('ix_instrument_prices_instrument_name'), 'instrument_prices', ['instrument_name'], unique=False)

    op.create_table(
        'portfolio_holdings',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('subscription_id', sa.UUID(), nullable=False),
        sa.Column('holding_type', sa.String(length=20), nullable=False),
        sa.Column('instrument_name', sa.String(length=200), nullable=False),
        sa.Column('units', sa.Float(), nullable=True),
        sa.Column('cost_price', sa.Float(), nullable=True),
        sa.Column('principal', sa.Float(), nullable=True),
        sa.Column('roi_pct', sa.Float(), nullable=True),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('maturity_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_portfolio_holdings_subscription_id'), 'portfolio_holdings', ['subscription_id'], unique=False)

    op.create_table(
        'portfolio_valuations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('subscription_id', sa.UUID(), nullable=False),
        sa.Column('valuation_date', sa.DateTime(timezone=True), nullable=False),
        sa.Column('equities_value', sa.Float(), nullable=False),
        sa.Column('fixed_income_value', sa.Float(), nullable=False),
        sa.Column('total_value', sa.Float(), nullable=False),
        sa.Column('breakdown', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_portfolio_valuations_subscription_id'), 'portfolio_valuations', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_portfolio_valuations_valuation_date'), 'portfolio_valuations', ['valuation_date'], unique=False)

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_index(op.f('ix_portfolio_valuations_valuation_date'), table_name='portfolio_valuations')
    op.drop_index(op.f('ix_portfolio_valuations_subscription_id'), table_name='portfolio_valuations')
    op.drop_table('portfolio_valuations')
    op.drop_index(op.f('ix_portfolio_holdings_subscription_id'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_instrument_prices_instrument_name'), table_name='instrument_prices')
    op.drop_table('instrument_prices')
