"""add portfolio breakdown visibility toggle

Revision ID: 51f8046f089c
Revises: ae49a2080cf2
Create Date: 2026-08-14 12:56:25.650605+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '51f8046f089c'
down_revision: Union[str, None] = 'ae49a2080cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default=sa.true() is required: this is a NOT NULL column being
    # added to a table that already has a row, so Postgres needs to know what
    # to put in that existing row. Defaults to True so current behaviour is
    # unchanged (clients keep seeing their breakdown) until an admin turns
    # it off deliberately.
    op.add_column(
        'system_settings',
        sa.Column('show_portfolio_breakdown', sa.Boolean(), nullable=False, server_default=sa.true())
    )

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_column('system_settings', 'show_portfolio_breakdown')
