"""add admin temp password flag

Revision ID: fd9731e55282
Revises: 970daf785701
Create Date: 2026-08-15 00:00:00.000000+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'fd9731e55282'
down_revision: Union[str, None] = '970daf785701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default=sa.false() is required: NOT NULL column on a table that
    # already has staff accounts in it. Defaults to False so existing staff
    # are not suddenly forced to change their password on next login — only
    # accounts created or reset after this point get flagged.
    op.add_column(
        'admin_users',
        sa.Column('temp_password_active', sa.Boolean(), nullable=False, server_default=sa.false())
    )

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_column('admin_users', 'temp_password_active')
