"""add minor and joint upload columns

Revision ID: 5ca396c7c24c
Revises: 901397a31e26
Create Date: 2026-08-11 06:12:15.287752+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '5ca396c7c24c'
down_revision: Union[str, None] = '901397a31e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('kyc_submissions', sa.Column('minor_passport_photo_url', sa.Text(), nullable=True))
    op.add_column('kyc_submissions', sa.Column('minor_birth_certificate_url', sa.Text(), nullable=True))
    op.add_column('kyc_submissions', sa.Column('joint_passport_photo_url', sa.Text(), nullable=True))
    op.add_column('kyc_submissions', sa.Column('joint_id_document_url', sa.Text(), nullable=True))

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_column('kyc_submissions', 'joint_id_document_url')
    op.drop_column('kyc_submissions', 'joint_passport_photo_url')
    op.drop_column('kyc_submissions', 'minor_birth_certificate_url')
    op.drop_column('kyc_submissions', 'minor_passport_photo_url')
