"""add mfa and temp password fields

Revision ID: 716b487d162b
Revises: 4b6e461f682d
Create Date: 2026-08-04 14:12:24.160428+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '716b487d162b'
down_revision: Union[str, None] = '4b6e461f682d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── admin_users (staff) ───────────────────────────────────────────────
    op.add_column('admin_users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('admin_users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column(
        'admin_users',
        sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
    )

    # ── users (clients) ──────────────────────────────────────────────────
    op.add_column(
        'users',
        sa.Column('temp_password_active', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.add_column('users', sa.Column('mfa_secret', sa.String(length=255), nullable=True))
    op.add_column(
        'users',
        sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false())
    )

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out — it's pre-existing
    # drift between the model and the DB, unrelated to this migration, and
    # should be reviewed and applied deliberately on its own.


def downgrade() -> None:
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'mfa_secret')
    op.drop_column('users', 'temp_password_active')

    op.drop_column('admin_users', 'mfa_enabled')
    op.drop_column('admin_users', 'mfa_secret')
    op.drop_column('admin_users', 'department')
