"""add user avatar url

Revision ID: 140a2853407c
Revises: 51f8046f089c
Create Date: 2026-08-14 00:00:00.000000+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '140a2853407c'
down_revision: Union[str, None] = '51f8046f089c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable, so no server_default is needed for the existing rows.
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_column('users', 'avatar_url')
