"""add board resolution signature columns

Revision ID: 901397a31e26
Revises: 9db261e83142
Create Date: 2026-08-09 00:59:36.350061+00:00
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '901397a31e26'
down_revision: Union[str, None] = '9db261e83142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('kyc_submissions', sa.Column('board_resolution_director_signature_url', sa.Text(), nullable=True))
    op.add_column('kyc_submissions', sa.Column('board_resolution_secretary_signature_url', sa.Text(), nullable=True))

    # NOTE: kyc_submissions.extra_data JSONB->JSON type-change alembic
    # autogenerated here has been intentionally left out again — same
    # pre-existing, unrelated drift as every previous migration.


def downgrade() -> None:
    op.drop_column('kyc_submissions', 'board_resolution_secretary_signature_url')
    op.drop_column('kyc_submissions', 'board_resolution_director_signature_url')
